apiVersion: v1
kind: Pod
metadata:
  name: pod-red
  namespace: production
  labels:
    app: web
spec:
  containers:
  - name: webapp-color-container
    image: kodekloud/webapp-color
    env:
    - name: APP_COLOR
      value: "red"

