apiVersion: v1
kind: Pod
metadata:
  name: webapp-color-pod
spec:
  containers:
  - name: webapp-color-container
    image: kodekloud/webapp-color
    env:
      - name: APP_COLOR
        value: "red"

