apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  labels:
    app: web
spec:
  containers:
  - name: webapp-container
    image: kodekloud/webapp-color
    ports:
      - containerPort: 8080
    env:
      - name: APP_COLOR
        valueFrom:
        configMapKeyRef:
          name: cm-color
          key: app_color
